# Generated by Django 3.2.16 on 2023-01-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
