# Generated by Django 3.2.16 on 2023-03-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
