# Generated by Django 3.2.16 on 2023-01-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230115_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creatted_date',
            new_name='created_date',
        ),
    ]
