# Generated by Django 3.2.16 on 2023-03-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='meesage',
            new_name='message',
        ),
    ]
